### ISSUE TITLE
The default table existence query is broken

### ISSUE THREAD

**Issue by jcoveney** [Cascading/cascading-jdbc#17] opened 2014-05-27 21:48 UTC
https://github.com/Cascading/cascading-jdbc/blob/2.5/cascading-jdbc-core/src/main/java/cascading/jdbc/JDBCTap.java#L642
which uses
https://github.com/Cascading/cascading-jdbc/blob/2.5/cascading-jdbc-core/src/main/java/cascading/jdbc/JDBCFactory.java#L51
as a default

I'm pretty sure that in any sql db the following:

```
select 1 from %s where 1 = 0
```

will always return no rows. The code as is checks to see if it returns exactly 1.

I don't know how we didn't hit this in testing (bad luck, I guess) but we hit it instantly in prod. I'm going to propose a fix in scalding for mysql that overrides the table existence query, but we should probably have a more reasonable default case that works in the major db's (at least mysql and postgres)

**Comment by fs111** [comment] 2014-05-28 11:41
The correct queries for the different db types are actually in the provider.properties files, which are currently only used by lingual. See here for example: https://github.com/Cascading/cascading-jdbc/blob/2.5/cascading-jdbc-mysql/src/main/resources/cascading/bind/provider.properties#L31 We have to extend TableDesc to find the correct query by itself and the problem is fixed.

**Comment by jcoveney** [comment] 2014-05-28 22:23
That's fair, but the current query is just straight up broken. I feel like it would be better to throw an error or make it explicitly required to override than to have a default that cannot work, period.

**Comment by fs111** [comment] 2014-06-03 12:32
I pushed a change which no longer needs custom SQL queries to test table existence. Please give cascading-jdbc-mysql-2.5-wip-79 a try.

**Comment by jcoveney** [comment] 2014-06-03 12:45
Ooh, I like this! Definitely the prostyle way to do it. I'm OOO until next week but will test it when I am back. Looks like the right way to do it though.

**Comment by fs111** [comment] 2014-06-12 18:53
Did you have a chance to look at this? I'd like to close this and push out a new release.

**Comment by fs111** [comment] 2014-06-19 14:48
@jcoveney ping. any news?

**Comment by jcoveney** [comment] 2014-06-19 14:50
Ack, sorry. You know how it is.

We have been running a version with a MySQL specific existence statement.

**Comment by fs111** [comment] 2014-06-19 14:51
would be great, if you could give this a spin. I'd like to do a cascading-jdbc release with this change included.

**Comment by jcoveney** [comment] 2014-06-19 22:47
I'll try to do this tomorrow.

2014-06-19 7:51 GMT-07:00 André Kelpe notifications@github.com:

**Comment by fs111** [comment] 2014-06-24 23:45
any news?

**Comment by jcoveney** [comment] 2014-06-25 01:49
Other issues have derailed my attention :( but tomorrow looks pretty
light...

**Comment by fs111** [comment] 2014-06-30 20:30
I want to release cascading-jdbc this week. It would be great if you could give this a spin before that. Let me know, what works for you.

**Closed as completed** 2014-07-07 16:33 UTC
